[package]
name = "electrs"
version = "0.4.1"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"

[features]
default = []
liquid = ["elements", "lazy_static"]

[dependencies]
arraydeque = "0.4"
arrayref = "0.3.6"
base64 = "0.12.0"
bincode = "1.2.1"
chan = "0.1"
chan-signal = "0.3"
clap = "2.31"
dirs = "2.0"
error-chain = "0.12.2"
futures = "0.1"
glob = "0.3"
hex = "0.4.2"
hyper = "0.12.33"
itertools = "0.9.0"
lazy_static = { version = "1.3.0", optional = true }
libc = "0.2.68"
log = "0.4"
lru = "0.3"
lru-cache = "0.1.1"
num_cpus = "1.12.0"
page_size = "0.4.2"
prometheus = "0.7"
rayon = "1.3.0"
rocksdb = "0.13.0"
rust-crypto = "0.2"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
stderrlog = "0.4.3"
sysconf = ">=0.3.4"
time = "0.1"
tiny_http = "0.6"
url = "2.1.1"

[dependencies.bitcoin]
version = "0.23.0"
features = ["use-serde"]

[dependencies.elements]
optional = true
version = "0.12.1"
features = ["serde-feature"]

[dev-dependencies]
tempfile = "3.0"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
